daysUntilStale: 28
daysUntilClose: 7
staleLabel: "stale"
issues:
  exemptLabels:
    - "up-for-grabs"
  markComment: >
    The issue has been marked as stale because it has not had recent activity, it will be closed if no further activity occurs.
pulls:
  markComment: >
    The pull request has been marked as stale because it has not had recent activity, it will be closed if no further activity occurs.
