# © Alexander Kozlenko. Licensed under the MIT License.

variables:
  Project.FilePath: "$(Build.SourcesDirectory)/global.proj"
  Project.Configuration: "Release"
steps:
- task: PowerShell@2
  inputs:
    pwsh: true
    targetType: "inline"
    script: |
        Write-Host ("##vso[task.setvariable variable=DotNetCoreSdkVersion;]" + (Get-Content -Raw "$(Build.SourcesDirectory)/global.json" | ConvertFrom-Json)."sdk"."version")
- task: DotNetCoreInstaller@0
  inputs:
    packageType: "sdk"
    version: "$(DotNetCoreSdkVersion)"
- task: DotNetCoreCLI@2
  inputs:
    command: "custom"
    custom: "build"
    arguments: "$(Project.FilePath) --configuration $(Project.Configuration) -property:ContinuousIntegrationBuild=true"
- task: DotNetCoreCLI@2
  inputs:
    command: "custom"
    custom: "test"
    arguments: "$(Project.FilePath) --configuration $(Project.Configuration) --no-build --logger trx --results-directory $(Agent.TempDirectory)"
- task: DotNetCoreCLI@2
  inputs:
    command: "custom"
    custom: "pack"
    arguments: "$(Project.FilePath) --configuration $(Project.Configuration) --no-build --include-symbols --output $(Build.ArtifactStagingDirectory)"
- task: PublishTestResults@2
  inputs:
    testRunner: "VSTest"
    testResultsFiles: "**/*.trx"
    searchFolder: "$(Agent.TempDirectory)"
- task: PublishBuildArtifacts@1